name: thinkcreative_technologies #changing it will force you to change appname in import statement inside every .dart file.
description: Admin app for Mobijet - Customer Support & Agents Management App

version: 1.0.2+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  excel: 2.0.0-null-safety-3
  circular_countdown_timer: 0.2.1
  camera: 0.10.0+1
  wechat_assets_picker: 8.0.0
  image_editor: 1.0.2
  extended_image: 6.2.0
  photo_view: 0.12.0
  open_file: 3.2.1
  file_saver: 0.1.1
  gallery_saver: 2.3.2
  flutter_sound: 8.5.0
  link_preview_generator: 1.2.0
  flutter_expanded_tile: 0.3.6
  chewie: 1.3.4
  video_player: 2.4.5
  styled_text: 5.0.0+1
  restart_app: 1.1.0
  # intl_phone_field: 2.1.0
  connectivity: 3.0.6
  flutter_switch: 0.3.2
  # cloud_functions: 3.0.3
  http_auth: 1.0.1
  cloud_firestore: 3.4.5
  page_transition: 2.0.5
  fluttertoast: 8.0.9
  firebase_messaging: 12.0.3
  eva_icons_flutter: 3.0.2
  flutter_rating_bar: 4.0.0
  cached_network_image: 3.2.1
  firebase_storage: 10.3.6
  file_picker: 4.5.1
  pinch_zoom: 1.0.0
  flutter_image_compress: 1.1.0
  path_provider: 2.0.10
  dio: 4.0.6
  url_launcher: 6.1.2
  jiffy: 4.1.0
  permission_handler: 8.3.0
  percent_indicator: 4.0.1
  flutter_video_info: 1.2.0
  youtube_player_flutter: 8.0.0
  font_awesome_flutter: 9.2.0
  ntp: 2.0.0
  bubble_tab_indicator: 0.1.6
  random_string: 2.3.1
  flutter_native_timezone: 2.0.0
  intl: 0.17.0
  flag: 5.0.1
  http: 0.13.4
  provider: 6.0.3
  firebase_auth: 3.6.4
  image_picker: 0.8.5+3
  device_info: 2.0.3
  universal_platform: 1.0.0+1
  flutter_linkify: 5.0.2
  dotted_border: 2.0.0+1
  flutter_cached_pdfview: 0.4.1
  share: 2.0.4
  launch_review: 3.0.1
  shared_preferences: 2.0.15
  firebase_core: 1.21.0
  package_info: 2.0.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  line_awesome_flutter: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  flutter_driver:
    sdk: flutter
  test: ^1.16.8
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "assets/RESKIN_ITEMS/appicon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/COMMON_ASSETS/
    - assets/RESKIN_ITEMS/
    - assets/flags/
    - lib/Localization/json_languages/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
    - family: PPoppins-Light
      fonts:
        - asset: fonts/Poppins/Poppins-Light.ttf
